const $=(s,p=document)=>p.querySelector(s);const $$=(s,p=document)=>[...p.querySelectorAll(s)];
const toolDefs={
'ai-room':{title:'Ask the Oracle',kicker:'AI / PRIVATE',icon:'✦',render:()=>`<div class="tool-form"><div class="chat-window" id="chatWindow"><div class="bubble ai">Welcome to the prototype room. Connect an API route later and this becomes a real private assistant.</div></div><label>Message<div style="display:flex;gap:8px"><input id="chatInput" placeholder="Ask anything…"><button class="tool-action primary" id="chatSend">Send</button></div></label><p style="color:#7f879f;font-size:11px;line-height:1.6">Demo mode: replies are local placeholders. The production version can use OpenAI, DeepSeek or another provider through a protected Vercel function.</p></div>`,init:()=>{$('#chatSend').onclick=sendDemo;$('#chatInput').addEventListener('keydown',e=>{if(e.key==='Enter')sendDemo()})}},
'media-desk':{title:'Media command',kicker:'MEDIA / DESK',icon:'◉',render:()=>`<div class="tool-form"><label>Video URL<input id="mediaUrl" placeholder="https://www.youtube.com/watch?v=…"></label><label>Format<select id="mediaFormat"><option value="bestvideo*+bestaudio/best">Best video + audio</option><option value="bestaudio">Audio only</option><option value="best[height<=1080]">Up to 1080p</option></select></label><div class="tool-actions"><button class="tool-action primary" id="makeCommand">Create command</button><button class="tool-action" id="copyCommand">Copy</button></div><div class="result-box" id="mediaResult">Paste a URL to generate a local yt-dlp command.</div><p style="color:#747d94;font-size:11px;line-height:1.6">Use only for content you own, public-domain material, or downloads expressly permitted by the platform and rights holder.</p></div>`,init:()=>{$('#makeCommand').onclick=makeMediaCommand;$('#copyCommand').onclick=()=>copyText($('#mediaResult').textContent)}},
'image-lab':{title:'Image Alchemy',kicker:'IMAGE / LOCAL',icon:'◇',render:()=>`<div class="tool-form"><label class="upload-zone"><input id="imageInput" type="file" accept="image/*" hidden><div><strong>Drop or choose an image</strong><br><small>Processed only in this browser</small></div></label><label>Quality <input id="imageQuality" type="range" min=".25" max=".95" value=".78" step=".01"></label><div class="tool-actions"><button class="tool-action primary" id="compressImage">Compress</button></div><div class="result-box" id="imageResult">No image selected.</div></div>`,init:()=>{const input=$('#imageInput'),zone=input.closest('.upload-zone');wireDropZone(zone,input,f=>{const dt=new DataTransfer();dt.items.add(f);input.files=dt.files;$('#imageResult').textContent=`${f.name} · ${formatBytes(f.size)}`});$('#compressImage').onclick=compressImage}},
'json-doctor':{title:'JSON Doctor',kicker:'DEV / CLEAN',icon:'{ }',render:()=>`<div class="tool-form"><label>JSON<textarea id="jsonInput" placeholder='{"hello":"world"}'></textarea></label><div class="tool-actions"><button class="tool-action primary" id="formatJson">Format</button><button class="tool-action" id="minifyJson">Minify</button><button class="tool-action" id="copyJson">Copy</button></div><div class="result-box" id="jsonStatus">Ready.</div></div>`,init:()=>{$('#formatJson').onclick=()=>transformJson(2);$('#minifyJson').onclick=()=>transformJson(0);$('#copyJson').onclick=()=>copyText($('#jsonInput').value)}},
'password-forge':{title:'Password Forge',kicker:'SECURE / LOCAL',icon:'⌁',render:()=>`<div class="tool-form"><label>Length <input id="passLength" type="range" min="12" max="64" value="24"></label><label><span><input id="passSymbols" type="checkbox" checked> Include symbols</span></label><div class="result-box" id="passwordResult" style="font-size:18px">Press generate.</div><div class="tool-actions"><button class="tool-action primary" id="generatePass">Generate</button><button class="tool-action" id="copyPass">Copy</button></div></div>`,init:()=>{$('#generatePass').onclick=generatePassword;$('#copyPass').onclick=()=>copyText($('#passwordResult').textContent);generatePassword()}},
'link-vault':{title:'Link Vault',kicker:'LINKS / LOCAL',icon:'∞',render:()=>`<div class="tool-form"><label>Title<input id="linkTitle" placeholder="Useful thing"></label><label>URL<input id="linkUrl" placeholder="https://…"></label><button class="tool-action primary" id="saveLink">Save locally</button><div class="saved-list" id="savedLinks"></div></div>`,init:()=>{$('#saveLink').onclick=saveLink;renderLinks()}},
'time-warp':{title:'Time Warp',kicker:'TIME / SHIFT',icon:'◷',render:()=>`<div class="tool-form"><label>Unix timestamp or date<input id="timeInput" placeholder="1721779200 or 2026-07-24"></label><button class="tool-action primary" id="convertTime">Convert</button><div class="result-box" id="timeResult">Enter a timestamp or date.</div></div>`,init:()=>{$('#convertTime').onclick=convertTime}},
'file-fingerprint':{title:'File Fingerprint',kicker:'FILE / VERIFY',icon:'⌾',render:()=>`<div class="tool-form"><label class="upload-zone"><input id="hashFile" type="file" hidden><div><strong>Drop or choose a file</strong><br><small>SHA-256 is calculated only on this device</small></div></label><div class="tool-meta-grid"><div class="tool-stat"><small>File</small><strong id="hashName">—</strong></div><div class="tool-stat"><small>Size</small><strong id="hashSize">—</strong></div><div class="tool-stat"><small>Algorithm</small><strong>SHA-256</strong></div></div><button class="tool-action primary" id="hashButton">Create fingerprint</button><div class="result-box hash-output" id="hashResult">No file selected.</div><button class="tool-action" id="copyHash">Copy hash</button></div>`,init:initFileFingerprint},
'text-reactor':{title:'Text Reactor',kicker:'TEXT / SHAPE',icon:'Aa',render:()=>`<div class="tool-form"><label>Text<textarea id="textInput" placeholder="Paste text here…"></textarea></label><div class="tool-meta-grid"><div class="tool-stat"><small>Words</small><strong id="wordCount">0</strong></div><div class="tool-stat"><small>Characters</small><strong id="charCount">0</strong></div><div class="tool-stat"><small>Lines</small><strong id="lineCount">0</strong></div></div><div class="tool-actions"><button class="tool-action primary" data-text-action="clean">Clean</button><button class="tool-action" data-text-action="upper">UPPER</button><button class="tool-action" data-text-action="lower">lower</button><button class="tool-action" data-text-action="title">Title Case</button><button class="tool-action" id="copyTextTool">Copy</button></div></div>`,init:initTextReactor},
'family-brain':{title:'Family Brain',kicker:'AI / MEMORY',icon:'◌',render:()=>`<div class="result-box"><strong>Planned upgrade</strong><br><br>A permissioned shared knowledge room for recipes, travel notes, household instructions and frequently asked questions. This needs authentication plus a database, so it is intentionally not faked in the static prototype.</div>`}
};
const toolOrder=['ai-room','media-desk','image-lab','json-doctor','password-forge','link-vault','time-warp','file-fingerprint','text-reactor','family-brain'];
function openTool(id){const d=toolDefs[id];if(!d)return;$('#modalTitle').textContent=d.title;$('#modalKicker').textContent=d.kicker;$('#modalContent').innerHTML=d.render();$('#toolModal').classList.add('open');$('#toolModal').setAttribute('aria-hidden','false');document.body.style.overflow='hidden';d.init?.();}
function closeModal(){$('#toolModal').classList.remove('open');$('#toolModal').setAttribute('aria-hidden','true');document.body.style.overflow=''}
$$('[data-tool]').forEach(c=>{c.addEventListener('click',e=>{if(!e.target.closest('button')||e.target.closest('.tool-card__launch'))openTool(c.dataset.tool)});c.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();openTool(c.dataset.tool)}});c.addEventListener('mousemove',e=>{const r=c.getBoundingClientRect();c.style.setProperty('--mx',`${e.clientX-r.left}px`);c.style.setProperty('--my',`${e.clientY-r.top}px`)})});
$$('[data-open-tool]').forEach(b=>b.onclick=()=>openTool(b.dataset.openTool));$$('[data-close-modal]').forEach(b=>b.onclick=closeModal);
function sendDemo(){const input=$('#chatInput');const v=input.value.trim();if(!v)return;const w=$('#chatWindow');w.insertAdjacentHTML('beforeend',`<div class="bubble user">${escapeHtml(v)}</div>`);input.value='';setTimeout(()=>{w.insertAdjacentHTML('beforeend',`<div class="bubble ai">Prototype reply: the visual and interaction layer is ready. Connect the protected API route and I can answer this for real.</div>`);w.scrollTop=w.scrollHeight},350);w.scrollTop=w.scrollHeight}
function makeMediaCommand(){const url=$('#mediaUrl').value.trim();if(!/^https?:\/\//i.test(url))return toast('Enter a valid URL');const fmt=$('#mediaFormat').value;$('#mediaResult').textContent=`yt-dlp -f "${fmt}" --merge-output-format mp4 "${url.replaceAll('"','')}"`}
async function compressImage(){const f=$('#imageInput').files[0];if(!f)return toast('Choose an image first');const q=Number($('#imageQuality').value);const bmp=await createImageBitmap(f);const c=document.createElement('canvas');c.width=bmp.width;c.height=bmp.height;c.getContext('2d').drawImage(bmp,0,0);c.toBlob(blob=>{const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=f.name.replace(/\.[^.]+$/, '')+'-compressed.webp';a.click();$('#imageResult').textContent=`${formatBytes(f.size)} → ${formatBytes(blob.size)} (${Math.max(0,Math.round((1-blob.size/f.size)*100))}% smaller)`},'image/webp',q)}
function wireDropZone(zone,input,onFile){const select=file=>{if(!file)return;onFile(file)};zone.onclick=e=>{if(e.target!==input)input.click()};input.onchange=e=>select(e.target.files[0]);['dragenter','dragover'].forEach(type=>zone.addEventListener(type,e=>{e.preventDefault();zone.classList.add('dragging')}));['dragleave','drop'].forEach(type=>zone.addEventListener(type,e=>{e.preventDefault();zone.classList.remove('dragging')}));zone.addEventListener('drop',e=>select(e.dataTransfer.files[0]))}
async function sha256Hex(buffer){if(globalThis.crypto?.subtle){const digest=await crypto.subtle.digest('SHA-256',buffer);return [...new Uint8Array(digest)].map(b=>b.toString(16).padStart(2,'0')).join('')}const bytes=new Uint8Array(buffer),length=bytes.length,paddedLength=Math.ceil((length+9)/64)*64,data=new Uint8Array(paddedLength);data.set(bytes);data[length]=0x80;const view=new DataView(data.buffer),bits=length*8;view.setUint32(paddedLength-8,Math.floor(bits/4294967296),false);view.setUint32(paddedLength-4,bits>>>0,false);const h=new Uint32Array([0x6a09e667,0xbb67ae85,0x3c6ef372,0xa54ff53a,0x510e527f,0x9b05688c,0x1f83d9ab,0x5be0cd19]),k=new Uint32Array([0x428a2f98,0x71374491,0xb5c0fbcf,0xe9b5dba5,0x3956c25b,0x59f111f1,0x923f82a4,0xab1c5ed5,0xd807aa98,0x12835b01,0x243185be,0x550c7dc3,0x72be5d74,0x80deb1fe,0x9bdc06a7,0xc19bf174,0xe49b69c1,0xefbe4786,0x0fc19dc6,0x240ca1cc,0x2de92c6f,0x4a7484aa,0x5cb0a9dc,0x76f988da,0x983e5152,0xa831c66d,0xb00327c8,0xbf597fc7,0xc6e00bf3,0xd5a79147,0x06ca6351,0x14292967,0x27b70a85,0x2e1b2138,0x4d2c6dfc,0x53380d13,0x650a7354,0x766a0abb,0x81c2c92e,0x92722c85,0xa2bfe8a1,0xa81a664b,0xc24b8b70,0xc76c51a3,0xd192e819,0xd6990624,0xf40e3585,0x106aa070,0x19a4c116,0x1e376c08,0x2748774c,0x34b0bcb5,0x391c0cb3,0x4ed8aa4a,0x5b9cca4f,0x682e6ff3,0x748f82ee,0x78a5636f,0x84c87814,0x8cc70208,0x90befffa,0xa4506ceb,0xbef9a3f7,0xc67178f2]),w=new Uint32Array(64),rotr=(x,n)=>(x>>>n)|(x<<(32-n));for(let offset=0;offset<paddedLength;offset+=64){for(let i=0;i<16;i++)w[i]=view.getUint32(offset+i*4,false);for(let i=16;i<64;i++){const s0=rotr(w[i-15],7)^rotr(w[i-15],18)^(w[i-15]>>>3),s1=rotr(w[i-2],17)^rotr(w[i-2],19)^(w[i-2]>>>10);w[i]=(w[i-16]+s0+w[i-7]+s1)>>>0}let [a,b,c,d,e,f,g,hh]=h;for(let i=0;i<64;i++){const S1=rotr(e,6)^rotr(e,11)^rotr(e,25),ch=(e&f)^(~e&g),t1=(hh+S1+ch+k[i]+w[i])>>>0,S0=rotr(a,2)^rotr(a,13)^rotr(a,22),maj=(a&b)^(a&c)^(b&c),t2=(S0+maj)>>>0;hh=g;g=f;f=e;e=(d+t1)>>>0;d=c;c=b;b=a;a=(t1+t2)>>>0}h[0]=(h[0]+a)>>>0;h[1]=(h[1]+b)>>>0;h[2]=(h[2]+c)>>>0;h[3]=(h[3]+d)>>>0;h[4]=(h[4]+e)>>>0;h[5]=(h[5]+f)>>>0;h[6]=(h[6]+g)>>>0;h[7]=(h[7]+hh)>>>0}return [...h].map(n=>n.toString(16).padStart(8,'0')).join('')}
function initFileFingerprint(){let file=null;const input=$('#hashFile'),zone=input.closest('.upload-zone');wireDropZone(zone,input,f=>{file=f;$('#hashName').textContent=f.name;$('#hashSize').textContent=formatBytes(f.size);$('#hashResult').textContent='Ready to calculate.'});$('#hashButton').onclick=async()=>{if(!file)return toast('Choose a file first');$('#hashResult').textContent='Calculating…';try{$('#hashResult').textContent=await sha256Hex(await file.arrayBuffer())}catch(error){$('#hashResult').textContent='Could not calculate the fingerprint: '+error.message}};$('#copyHash').onclick=()=>copyText($('#hashResult').textContent)}
function initTextReactor(){const input=$('#textInput');const update=()=>{const text=input.value;$('#wordCount').textContent=(text.trim().match(/\S+/g)||[]).length;$('#charCount').textContent=text.length;$('#lineCount').textContent=text?text.split(/\r?\n/).length:0};input.oninput=update;$$('[data-text-action]').forEach(b=>b.onclick=()=>{const action=b.dataset.textAction;let text=input.value;if(action==='clean')text=text.replace(/[ \t]+/g,' ').replace(/ *\n */g,'\n').replace(/\n{3,}/g,'\n\n').trim();if(action==='upper')text=text.toUpperCase();if(action==='lower')text=text.toLowerCase();if(action==='title')text=text.toLowerCase().replace(/\b\p{L}/gu,c=>c.toUpperCase());input.value=text;update()});$('#copyTextTool').onclick=()=>copyText(input.value);update()}
function transformJson(space){try{const o=JSON.parse($('#jsonInput').value);$('#jsonInput').value=JSON.stringify(o,null,space||undefined);$('#jsonStatus').textContent='Valid JSON ✓'}catch(e){$('#jsonStatus').textContent='Invalid JSON: '+e.message}}
function generatePassword(){const n=Number($('#passLength').value);const alpha='ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz23456789';const sym='!@#$%&*_-+=?';const chars=alpha+($('#passSymbols').checked?sym:'');const arr=new Uint32Array(n);crypto.getRandomValues(arr);$('#passwordResult').textContent=[...arr].map(x=>chars[x%chars.length]).join('')}
let memoryLinks=[];function getLinks(){try{return JSON.parse(localStorage.getItem('nexus-links')||'[]')}catch{return memoryLinks}}function storeLinks(links){memoryLinks=links;try{localStorage.setItem('nexus-links',JSON.stringify(links))}catch{}}function saveLink(){const title=$('#linkTitle').value.trim()||'Untitled';const url=$('#linkUrl').value.trim();if(!/^https?:\/\//i.test(url))return toast('Enter a valid URL');const links=getLinks();links.unshift({title,url});storeLinks(links.slice(0,30));renderLinks();$('#linkTitle').value='';$('#linkUrl').value=''}function renderLinks(){const el=$('#savedLinks');if(!el)return;const links=getLinks();el.innerHTML=links.length?links.map((l,i)=>`<div class="saved-link"><a href="${escapeAttr(l.url)}" target="_blank" rel="noopener">${escapeHtml(l.title)}</a><button data-delete-link="${i}">×</button></div>`).join(''):'<div class="result-box">No links saved yet.</div>';$$('[data-delete-link]',el).forEach(b=>b.onclick=()=>{links.splice(Number(b.dataset.deleteLink),1);storeLinks(links);renderLinks()})}
function convertTime(){const v=$('#timeInput').value.trim();let d;if(/^\d{10,13}$/.test(v))d=new Date(Number(v)*(v.length===10?1000:1));else d=new Date(v);$('#timeResult').innerHTML=isNaN(d)?'Could not parse that value.':`Local: ${escapeHtml(d.toLocaleString())}<br>UTC: ${escapeHtml(d.toUTCString())}<br>Unix: ${Math.floor(d.getTime()/1000)}`}
async function copyText(t){try{await navigator.clipboard.writeText(t);toast('Copied to clipboard')}catch{const ta=document.createElement('textarea');ta.value=t;ta.style.position='fixed';ta.style.opacity='0';document.body.append(ta);ta.select();document.execCommand('copy');ta.remove();toast('Copied to clipboard')}}
function formatBytes(n){return n<1024?n+' B':n<1048576?(n/1024).toFixed(1)+' KB':(n/1048576).toFixed(1)+' MB'}function escapeHtml(s){return s.replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]))}function escapeAttr(s){return escapeHtml(s).replace(/'/g,'&#39;')}
function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>t.classList.remove('show'),1800)}
function setFilter(){const f=$('.filter.active').dataset.filter,q=$('#toolSearch').value.toLowerCase();$$('[data-tool]').forEach(c=>{const matchCat=f==='all'||c.dataset.category.includes(f);const matchQ=!q||c.textContent.toLowerCase().includes(q);c.hidden=!(matchCat&&matchQ)})}$$('.filter').forEach(b=>b.onclick=()=>{$$('.filter').forEach(x=>x.classList.remove('active'));b.classList.add('active');setFilter()});$('#toolSearch').oninput=setFilter;
function openCommand(){renderCommands();$('#commandPalette').classList.add('open');$('#commandPalette').setAttribute('aria-hidden','false');setTimeout(()=>$('#commandInput').focus(),0)}function closeCommand(){$('#commandPalette').classList.remove('open');$('#commandPalette').setAttribute('aria-hidden','true')}function renderCommands(){const q=($('#commandInput')?.value||'').toLowerCase();const items=toolOrder.filter(id=>toolDefs[id].title.toLowerCase().includes(q));$('#commandResults').innerHTML=items.map(id=>`<button class="command-item" data-command-tool="${id}"><span>${toolDefs[id].icon}</span>${toolDefs[id].title}<small>${toolDefs[id].kicker}</small></button>`).join('');$$('[data-command-tool]').forEach(b=>b.onclick=()=>{closeCommand();openTool(b.dataset.commandTool)})}$('#commandButton').onclick=openCommand;$$('[data-close-command]').forEach(b=>b.onclick=closeCommand);$('#commandInput').oninput=renderCommands;document.addEventListener('keydown',e=>{if(e.key==='/'&&!['INPUT','TEXTAREA'].includes(document.activeElement.tagName)){e.preventDefault();openCommand()}if(e.key==='Escape'){closeCommand();closeModal()}});
$('#surpriseButton').onclick=()=>openTool(toolOrder[Math.floor(Math.random()*7)]);
setInterval(()=>{$('#liveClock').textContent=new Date().toLocaleTimeString([],{hour12:false})},1000);
const navLinks=$$('.nav a');const sections=['tools','rooms','about'].map(id=>document.getElementById(id));const navObserver=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){navLinks.forEach(a=>a.classList.toggle('active',a.getAttribute('href')==='#'+entry.target.id))}}),{rootMargin:'-35% 0px -55%'});sections.forEach(s=>navObserver.observe(s));addEventListener('scroll',()=>$('.topbar').classList.toggle('compact',scrollY>40),{passive:true});if(matchMedia('(pointer:fine)').matches){addEventListener('pointermove',e=>{const x=(e.clientX/innerWidth-.5)*10,y=(e.clientY/innerHeight-.5)*8;$('.space__image').style.transform=`scale(1.05) translate(${-x}px,${-y}px)`},{passive:true})}
const io=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting)e.target.classList.add('visible')}),{threshold:.12});$$('.reveal').forEach(el=>io.observe(el));
